# Generated by Django 4.0.3 on 2022-05-29 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0015_alter_compras_date_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='comentario',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='compras',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 29, 14, 37, 44, 905791)),
        ),
    ]
