# Generated by Django 4.0.3 on 2022-05-29 13:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0016_alter_comentarios_comentario_alter_compras_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentarios',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 29, 14, 39, 41, 984995)),
        ),
        migrations.AlterField(
            model_name='compras',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 5, 29, 14, 39, 41, 984995)),
        ),
    ]
