# Generated by Django 4.0.3 on 2022-06-02 15:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0017_comentarios_date_alter_compras_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentarios',
            name='comentario',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='comentarios',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 6, 2, 16, 18, 12, 366440)),
        ),
        migrations.AlterField(
            model_name='compras',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 6, 2, 16, 18, 12, 367437)),
        ),
    ]
